version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dictionary
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: '3333'
      DATABASE_URL: postgres://postgres:postgres@db:5432/dictionary
      JWT_SECRET: supersecret
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      DICTIONARY_API_BASE: https://api.dictionaryapi.dev/api/v2/entries/en
    depends_on:
      - db
      - redis
    ports:
      - '3333:3333'

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE: http://backend:3333/api
    depends_on:
      - backend
    ports:
      - '3000:3000'

volumes:
  dbdata:
