version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dictionary
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d dictionary']
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
    environment:
      PORT: 3000
      JWT_SECRET: supersecret
      JWT_EXPIRES: 7d
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: dictionary
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_TTL_SECONDS: 86400
      WORDLIST_URL: https://raw.githubusercontent.com/meetDeveloper/freeDictionaryAPI/master/meta/wordList/english.txt
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '3000:3000'
    command: >
      sh -c "
        node node_modules/typeorm/cli.js -d dist/ormconfig.js migration:run &&
        node dist/src/main.js
      "
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'node -e "http=require(''http'');http.get(''http://localhost:3000/'',r=>process.exit(r.statusCode===200?0:1)).on(''error'',()=>process.exit(1))"',
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  seed:
    build:
      context: .
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: dictionary
      WORDLIST_URL: https://raw.githubusercontent.com/meetDeveloper/freeDictionaryAPI/master/meta/wordList/english.txt
    depends_on:
      api:
        condition: service_healthy
    command: >
      sh -c "
        node dist/src/entries/seed-words.js
      "
    restart: 'no'

volumes:
  pgdata:
